baseURL = "https://ashtadhyayi.github.io/"
languageCode = "en-us"
title = "अष्टाध्यायी - मूलस्रोतः"
theme = "ananke"
publishDir = "docs"
ignorefiles = [ "vritti/scripts/.*" ]
[params]
  githubEditMePathBase = "https://github.com/sanskrit/ashtadhyayi/blob/master/"
