baseURL = "file:///storage/emulated/0/sanskrit/ashtadhyayi"
languageCode = "en-us"
title = "अष्टाध्यायी - मूलस्रोतः"
theme = "ashtadhyayi"
publishDir = "build_offline_android"
ignorefiles = [ ".git.*" ]
[params]
  githubEditMePathBase = "https://github.com/sanskrit/ashtadhyayi/edit/master/"
  env = "production"
[taxonomies]
  index = "indices"
  sutra = "sutras"
