baseURL = "https://ashtadhyayi.github.io/ui/"
languageCode = "en-us"
title = "अष्टाध्यायी - मूलस्रोतः"
theme = "ananke"
publishDir = "docs"
ignorefiles = [ "vritti/scripts/.*" ]
[params]
  githubEditMePathBase = "https://github.com/sanskrit/ashtadhyayi/edit/master/"
  env = "production"
